### ISSUE TITLE
Does not work on file:// URLs in Chrome

### ISSUE THREAD

**Issue by rainyeveryday** [kmltml/clipboard-inserter#2]
In Chrome, I get the following error message when I try to enable the extension on a file:// URL:

```
Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of the page. Extension manifest must request permission to access the respective host.
    at toggleTab (chrome-extension://<...>/bg/monitor.js:44:14)
    at Object.chrome.tabs.query [as callback] (chrome-extension://<...>/bg/monitor.js:25:11)
```

Oddly enough, this doesn't seem to happen by default when loading an unpacked extension in development. After a quick search online it looks like it's necessary to [request permission to access "file://\*/\*" URLs](https://stackoverflow.com/a/19493206), which needs to be manually toggled by the user in the settings (though that post seems to be a few years old, not sure if anything has changed or what the best practices are).

**Comment by kmltml** [comment]
It seems, like the previous version worked on my chrome, but i pushed the update to web store. Please check if it works for you now, and if it does i'll merge the pull request officially.

**Comment by rainyeveryday** [comment]
It's working for me now, thanks for publishing the update.

**Comment by ghost** [comment]
I'm having the same problem in Firefox. Older versions of the addon worked fine.

**Comment by rainyeveryday** [comment]
What OS/version of Firefox is that happening in? It seems to work fine for me on Windows 10 with 64-bit Firefox versions 60.0.2 and 61.0.1, at least by my own testing.

**Comment by panhartstuff** [comment]
It still doesn't work, are you planning to fix this?

**Comment by rainyeveryday** [comment]
@panhartstuff Could you provide some other information like your Firefox and OS version to help debug?

**Comment by panhartstuff** [comment]
I'm using Google Chrome Version 69.0.3497.100 and Windows 10
There's no error messages or anything. But basically, the extension doesn't do anything on offline .html files (file:/// url), even blank ones. It works perfectly on any online sites, though.

**Comment by kmltml** [comment]
I was able to reproduce the error, but going to the extension settings (chrome://extensions, then click the "details" button on Clipboard Inserter extension card) and switching "Allow access to file URLs" on seems to have fixed it. Could you check if that works for you @panhartstuff ?

**Comment by panhartstuff** [comment]
Thanks, that fixed it. Should've thought to meddle with the settings more, sorry for the trouble

**Comment by kmltml** [comment]
No problem, glad i could help.
