### ISSUE TITLE
a small request pls

### ISSUE THREAD

**Issue by ggezisthename** [kmltml/clipboard-inserter#6]
Hello .

I have ben using your google chrome add for Somme and honestly its great help for language learner like me i have ben using it with also another addon called yomichan 
to copy sentences the only problem i have is the yomichan doesn't now when the sentence starts or ends so it takes all the lines in the page what i need if possible is to add dot . between lines or at the benign or end of lines this really important to me  and i spend hours on it to no results.
if its possible i really need your help .
this is the html file im using 
https://uploadfiles.io/qr4yt

**Comment by kmltml** [comment]
I fixed up your script a little bit. You have to replace everything between `<script>` and `</script>` in your html file with this:
https://gist.github.com/kmltml/4121d43d9adf41ee0d582144c4004272
Please tell me if it works for you.

**Comment by ggezisthename** [comment]
thank very very much this made my life much much easier .

and sorry for not replying earlier.
